# config.yml

backend:
  name: github
  repo: mehrhygge/mehrhygge.github.io
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: 'assets/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Separator', name: 'excerpt_separator', widget: 'hidden', default: '<!--more-->' } 
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Highlight', name: 'featured', widget: 'boolean', default: false }
      - { label: 'Highlight Beschreibung', name: 'featured_description', widget: 'text', default: '' }
      - { label: 'Highlight Bild', name: 'featured_image', widget: 'image', default: '' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Seiten'
    editor:
      preview: false
    files:
      - label: 'Willkommen'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'featured' }
          - { label: 'Inhalt', name: 'body', widget: 'markdown' }
