# config.yml

site_id: mehrhygge.netlify.com

backend:
  name: github
  repo: mehrhygge/mehrhygge.github.io
  site_id: mehrhygge.netlify.com
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Seiten'
    editor:
      preview: false
    files:
      - label: 'Willkommen'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'featured' }
          - { label: 'Inhalt', name: 'body', widget: 'markdown' }
