# config.yml

backend:
  name: github
  repo: mehrhygge/mehrhygge.github.io
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: MehrHygge }
